export const ColorScheme = {
  "purple-rose": {
    bgGradient: "from-purple-100 to-pink-100",
    headerGradient: "from-purple-500 to-pink-500",
    accentText: "text-purple-600",
    accentBorder: "border-pink-200",
    progressBg: "bg-pink-200",
    progressFill: "from-purple-500 to-pink-500",
    tagBg: "bg-pink-100",
    tagText: "text-purple-600",
  },
  "blue-teal": {
    bgGradient: "from-blue-100 to-teal-100",
    headerGradient: "from-blue-500 to-teal-500",
    accentText: "text-blue-600",
    accentBorder: "border-teal-200",
    progressBg: "bg-teal-200",
    progressFill: "from-blue-500 to-teal-500",
    tagBg: "bg-teal-100",
    tagText: "text-blue-600",
  },
  "orange-yellow": {
    bgGradient: "from-orange-100 to-yellow-100",
    headerGradient: "from-orange-500 to-yellow-500",
    accentText: "text-orange-600",
    accentBorder: "border-yellow-200",
    progressBg: "bg-yellow-200",
    progressFill: "from-orange-500 to-yellow-500",
    tagBg: "bg-yellow-100",
    tagText: "text-orange-600",
  },
  "green-lime": {
    bgGradient: "from-green-100 to-lime-100",
    headerGradient: "from-green-500 to-lime-500",
    accentText: "text-green-600",
    accentBorder: "border-lime-200",
    progressBg: "bg-lime-200",
    progressFill: "from-green-500 to-lime-500",
    tagBg: "bg-lime-100",
    tagText: "text-green-600",
  },
};
